### ISSUE TITLE
Decide for license

### ISSUE THREAD

**Issue by seichelbaum** [NeuroanatomyAndConnectivity/DirectionalityIndicator#1]
We should decide for a final license.

GPL v3 is currently set. There is some kind of controversial discussion on GPL v2 vs v3. MIT, BSD or Apache are also reasonable options.

**Comment by seichelbaum** [comment]
Personally, I prefer GPL over MIT, BSD and others. This is mainly due to the fact that they allow easier integration of other codes (a lot of other codes are GPL and LGPL) into a project. On most Linux, integration of external code is not necessary, since the package repositories provide nearly everything already. On Windows and Mac OS X this is different. For a portable software, it often is required to integrate external code into the project ... unfortunately.  By using GPL v3, we ensure compatibility with a lot of other licenses.

**Comment by margulies** [comment]
That sounds like a reasonable argument for GPL.

**Comment by chrisgorgo** [comment]
I would recommend using at least LGPL - otherwise any software using MIT, BST, Apache etc (any non GPL) license will not be able to link with your software. Sticking to pure GPL is noble and principled decision but might be counterproductive.

**Comment by seichelbaum** [comment]
Yes LGPL is an option too.

**Comment by seichelbaum** [comment]
Talked with Daniel about this. We keep LGPL now.

Close.
